### ISSUE TITLE
Pipenv not found when running action

### ISSUE THREAD

**Issue by RubenVanEldik** [smelly-python/smell-my-pr#2]
Hi there!

Thank you for developing this awesome Action! I tried adding it to my application today, but I can't get it to run properly. Every time I keep getting the error that `pipenv: command not found`, do you have any idea how I can solve this? I have googled it, but I can't find a clear answer.

This is my workflow:
```
name: Linting
on: pull_request
jobs:
  smelly-python:
    name: Smelly Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: smelly-python/smell-my-pr@v1.0.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        command: pipenv run smelly-python -d .
```

This is the error I get on GitHub:
```
Run smelly-python/smell-my-pr@v1.0.0
  with:
    github-token: ***
    command: pipenv run smelly-python -d .
Run pipenv run smelly-python -d .
  pipenv run smelly-python -d .
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
/home/runner/work/_temp/c07ab0cc-ee76-447c-9622-43c0184a1f8c.sh: line 1: pipenv: command not found
Error: Process completed with exit code 127.
```
